"""provider_connections

Revision ID: 7292562c98ec
Revises: abd413a14ea9
Create Date: 2026-07-24 23:07:44.112549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7292562c98ec'
down_revision: Union[str, Sequence[str], None] = 'abd413a14ea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_connections',
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('manual', 'plaid', name='provider'), nullable=False),
    sa.Column('encrypted_credentials', sa.LargeBinary(), nullable=False),
    sa.Column('status', sa.Enum('active', 'error', 'disconnected', name='conn_status'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_connections_household_id'), 'provider_connections', ['household_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_connections_household_id'), table_name='provider_connections')
    op.drop_table('provider_connections')
    # ### end Alembic commands ###
    op.execute('DROP TYPE IF EXISTS provider')
    op.execute('DROP TYPE IF EXISTS conn_status')
